name: Deploy to Debian 12

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_PATH: "/Git/Docker-project"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        env:
          DEPLOY_PATH: "/Git/Docker-project"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to Debian server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_HADES_USER }}@${{ secrets.HOST_HADES_IP }} "mkdir -p ${DEPLOY_PATH}"
          scp -r ./ ${{ secrets.HOST_HADES_USER }}@${{ secrets.HOST_HADES_IP }}:${DEPLOY_PATH}

      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_HADES_USER }}@${{ secrets.HOST_HADES_IP }} 'bash -s' < ./deploy_script.sh
