name: Deploy to Debian 12

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_PATH: "/Git/Docker-project"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure proper permissions and create directories
        run: |
          # Connexion à Hades et création du dossier avec les bonnes permissions
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_HADES_USER }}@${{ secrets.HOST_HADES_IP }} "sudo mkdir -p ${DEPLOY_PATH} && sudo chown -R ${{ secrets.HOST_HADES_USER }}:${{ secrets.HOST_HADES_USER }} ${DEPLOY_PATH} && sudo chmod -R 775 ${DEPLOY_PATH}"

      - name: Copy files to Debian server
        run: |
          scp -r ./ ${{ secrets.HOST_HADES_USER }}@${{ secrets.HOST_HADES_IP }}:/home/${{ secrets.HOST_HADES_USER }}/Git/Docker-project

      - name: Deploy Docker container on Debian server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_HADES_USER }}@${{ secrets.HOST_HADES_IP }} << 'EOF'
            # Naviguer vers le répertoire du projet
            cd /home/${{ secrets.HOST_HADES_USER }}/Git/Docker-project

            # Construire l'image Docker
            docker build -t my-server .

            # Lancer le conteneur Docker
            docker run -d -p 3000:3000 --name my-server-container my-server
          EOF
