name: Deploy to Debian 12

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_PATH: "/Git/Docker-project"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_HADES_IP }}
          username: ${{ secrets.HOST_HADES_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Vérifie si le dossier existe, sinon le crée
            mkdir -p /Git/Docker-project

            # Aller dans le dossier et récupérer la dernière version du code
            cd /Git/Docker-project
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone git@github.com:Tomaks28/ton-repo.git .
            fi
