name: Deploy to Hades - Debian 12

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_PATH: "/Git/Docker-project"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: true
          separator: ","

      - name: Copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_HADES_IP }}
          username: ${{ secrets.HOST_HADES_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ${{ steps.changed-files.outputs.all_changed_files }}
          target: "/Git/Docker-project"
