name: Deploy to Hades - Debian 12

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_PATH: "/Git/Docker-project"
      SSH_PORT: 22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_HADES_IP }}
          username: ${{ secrets.HOST_HADES_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./"
          target: "/home/${{secrets.HOST_HADES_USER}}/${{secrets.DEPLOY_PATH}}"

      - name: Docker - Build and Run
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST_HADES_IP }}
          username: ${{ secrets.HOST_HADES_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{secrets.HOST_HADES_USER}}/${{secrets.DEPLOY_PATH}}

            # Construire l'image Docker
            docker build -t hades .

            # Supprimer l'ancien conteneur s'il existe
            echo "Stopping and removing old container..."
            docker stop heuristic_hoover || true
            docker rm heuristic_hoover || true

            # Lancer le nouveau conteneur
            echo "Starting new container..."
            docker run -d -p 4000:4000 --name heuristic_hoover hades
